.SUFFIXES : ReynoldsBHW3.cpp

CC = g++ ReynoldsBHW3.cpp

CXXFLAGS = -g -std=c++11

OBJS = ReynoldsBHW3.o

TARGET = output

$(TARGET): $(OBJS)
	$(CC) -o $@ $(OBJS)

.cpp.o:
	$(CC) -c $(CXXFLAGS) $(INCDIR) $<

clean:
	rm -f $(OBJS) $(TARGET) core